//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabinetKosmetyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkty_do_zabiegu
    {
        public int id_produkty_do_zabiegu { get; set; }
        public Nullable<int> produkt { get; set; }
        public Nullable<int> nazwazabiegu { get; set; }
    
        public virtual produkty produkty { get; set; }
        public virtual typ_zabiegu typ_zabiegu { get; set; }
    }
}
