//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabinetKosmetyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class typ_zabiegu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public typ_zabiegu()
        {
            this.produkty_do_zabiegu = new HashSet<produkty_do_zabiegu>();
            this.zabiegi = new HashSet<zabiegi>();
        }
    
        public int id_zabiegu { get; set; }
        public string nazwa { get; set; }
        public string typ { get; set; }
        public short czastrwania { get; set; }
        public decimal cena { get; set; }
        public Nullable<int> pracownik { get; set; }
        public Nullable<int> gabinety { get; set; }
    
        public virtual gabinety gabinety1 { get; set; }
        public virtual pracownicy pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produkty_do_zabiegu> produkty_do_zabiegu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zabiegi> zabiegi { get; set; }
    }
}
